services:
  exam-builder:
    image: tahmidachoudhury/exambuilder-backend:latest
    container_name: exam-builder-backend
    restart: unless-stopped
    ports:
      - "3002:3002"
    env_file:
      - .env
